// var User = describe('User', function () {
//     property('email', String, {index:true, limit:150});
//     property('firstname', String);
//     property('lastname', String);
//     property('username', String, {index:true, limit:150});
//     property('password', String);
//     property('createdAt', Date, {default: function () { return new Date() }});
//     property('updatedAt', Date, {default: function () { return new Date() }});
//     property('activated', Boolean, {default:false});
//     property('accounttype', String, {default:"regular"});
//     property('description', String);
//     property('url', String);
//     property('image', String);
//     property('image_https', String);
//     property('twitterAccessToken', String);
//     property('twitterAccessTokenSecret', String);
//     property('twitterUsername', String);
//     property('twitterId', String, { index: true });
//     property('facebookAccessToken', String);
//     property('facebookUsername', String);
//     property('facebookId', String, { index: true });
//     property('foursquareAccessToken', String);
//     property('foursquareId', String, { index: true });
//     property('soundcloudId', String);
//     property('soundcloudAccessToken', String);
//     property('soundcloudAccessTokenSecret', String);
//     property('meetupId', String);
//     property('meetupAccessToken', String);
//     property('meetupAccessTokenSecret', String);
//     property('linkedinId', String);
//     property('linkedinAccessToken', String);
//     property('linkedinAccessTokenSecret', String);
//     property('instagramId', String);
//     property('instagramAccessToken', String);
//     property('githubId', String);
//     property('githubUsername', String);
//     property('githubAccessToken', String);
//     property('tumblrUsername', String);
//     property('tumblrAccessToken', String);
//     property('tumblrAccessTokenSecret', String);
//     property('goodreadsId', String);
//     property('goodreadsAccessToken', String);
//     property('goodreadsAccessTokenSecret', String);
// });

module.exports = {};